# Generated by Django 5.0.1 on 2024-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_history',
            name='project_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
